# Build UEFI for Xiaomi Mi 10T / Mi 10T Pro (apollo) — SM8250
name: SM8250 Xiaomi 10T (apollo)

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Platforms/KonaPkg/Device/xiaomi-apollo/**'
      - '.github/workflows/sm8250_xiaomi_apollo.yml'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Indicate that we are running in CI
env:
  WM_CI_BUILD: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Build SB/NOSB uefi for Xiaomi 10T (apollo).
        run: bash scripts/ci_setup.sh && ./build_uefi.py -d xiaomi-apollo -t DEBUG

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: uefi-images-apollo
          path: Build/*/ci_artifacts
          compression-level: 9
